read_rate: 15
write_rate: 25

joints:
  arm_shoulder_pan_joint:
    id: 1
    type: dynamixel
    neutral: 512
    min_angle: -150
    max_angle: 150
    max_speed: 90
  arm_shoulder_lift_joint:
    id: 2
    type: dynamixel
    min_angle: -120
    max_angle: 120
    max_speed: 90

controllers:
  arm_controller: 
    type: follow_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
    action_name: arm_controller/follow_joint_trajectory
    onboard: False
